# Generated by Django 4.2.8 on 2023-12-14 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookreservation', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.CharField(max_length=50),
        ),
    ]
