# Generated by Django 4.2.8 on 2023-12-14 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookreservation', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
