# Generated by Django 4.2.8 on 2023-12-14 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookreservation', '0002_delete_choice_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('author_name', models.CharField(max_length=50)),
                ('currently_checked_out', models.BooleanField()),
                ('number_of_times_checked_out', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('major', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
